#ifndef AXI_STREAM_SOURCE_MONITOR_HW_H_
#define AXI_STREAM_SOURCE_MONITOR_HW_H_

#include "xil_types.h"
#include "xil_io.h"

/* Register offsets */
#define AXI_STREAM_SOURCE_MONITOR_AP_CTRL_REG_OFFSET 0x0
#define AXI_STREAM_SOURCE_MONITOR_GIE_REG_OFFSET 0x4
#define AXI_STREAM_SOURCE_MONITOR_IP_INTR_EN_REG_OFFSET 0x8
#define AXI_STREAM_SOURCE_MONITOR_IP_INTR_STS_REG_OFFSET 0xc
#define AXI_STREAM_SOURCE_MONITOR_CONTROL_REG_OFFSET 0x10

/* Control Register bitfields */
#define AXI_STREAM_SOURCE_MONITOR_AP_CTRL_START_MASK 0x01
#define AXI_STREAM_SOURCE_MONITOR_AP_CTRL_DONE_MASK 0x02
#define AXI_STREAM_SOURCE_MONITOR_AP_CTRL_IDLE_MASK 0x04
#define AXI_STREAM_SOURCE_MONITOR_AP_CTRL_READY_MASK 0x08
#define AXI_STREAM_SOURCE_MONITOR_AP_CTRL_AUTO_RESTART_MASK 0x80

/* Global interrupt enable register bitfields */
#define AXI_STREAM_SOURCE_MONITOR_GIE_ENABLE_MASK 0x01

/* IP interrupt enable register bitfields */
#define AXI_STREAM_SOURCE_MONITOR_IP_INTR_EN_AP_DONE_MASK 0x1
#define AXI_STREAM_SOURCE_MONITOR_IP_INTR_EN_AP_READY_MASK 0x2
#define AXI_STREAM_SOURCE_MONITOR_IP_INTR_EN_ALL_MASK 0x3

/* IP interrupt status register bitfields */
#define AXI_STREAM_SOURCE_MONITOR_IP_INTR_STS_AP_DONE_MASK 0x1
#define AXI_STREAM_SOURCE_MONITOR_IP_INTR_STS_AP_READY_MASK 0x2
/* CONTROL register bitfields */
#define AXI_STREAM_SOURCE_MONITOR_CONTROL_ENABLE_MASK 0x1
#define AXI_STREAM_SOURCE_MONITOR_CONTROL_FREERUN_MASK 0x2
#define AXI_STREAM_SOURCE_MONITOR_CONTROL_GENERATORSELECT_MASK 0x4

#endif /* end of protection macro */
