#ifndef AXI_STREAM_SINK_MONITOR_HW_H_
#define AXI_STREAM_SINK_MONITOR_HW_H_

#include "xil_types.h"
#include "xil_io.h"

/* Register offsets */
#define AXI_STREAM_SINK_MONITOR_AP_CTRL_REG_OFFSET 0x0
#define AXI_STREAM_SINK_MONITOR_GIE_REG_OFFSET 0x4
#define AXI_STREAM_SINK_MONITOR_IP_INTR_EN_REG_OFFSET 0x8
#define AXI_STREAM_SINK_MONITOR_IP_INTR_STS_REG_OFFSET 0xc
#define AXI_STREAM_SINK_MONITOR_CONTROL_REG_OFFSET 0x10
#define AXI_STREAM_SINK_MONITOR_STATUS_REG_OFFSET 0x18
#define AXI_STREAM_SINK_MONITOR_NUMFRAMES_REG_OFFSET 0x20
#define AXI_STREAM_SINK_MONITOR_BEATCOUNT_REG_OFFSET 0x28
#define AXI_STREAM_SINK_MONITOR_MISSCOUNT_REG_OFFSET 0x30
#define AXI_STREAM_SINK_MONITOR_ERRORCOUNT_REG_OFFSET 0x38

/* Control Register bitfields */
#define AXI_STREAM_SINK_MONITOR_AP_CTRL_START_MASK 0x01
#define AXI_STREAM_SINK_MONITOR_AP_CTRL_DONE_MASK 0x02
#define AXI_STREAM_SINK_MONITOR_AP_CTRL_IDLE_MASK 0x04
#define AXI_STREAM_SINK_MONITOR_AP_CTRL_READY_MASK 0x08
#define AXI_STREAM_SINK_MONITOR_AP_CTRL_AUTO_RESTART_MASK 0x80

/* Global interrupt enable register bitfields */
#define AXI_STREAM_SINK_MONITOR_GIE_ENABLE_MASK 0x01

/* IP interrupt enable register bitfields */
#define AXI_STREAM_SINK_MONITOR_IP_INTR_EN_AP_DONE_MASK 0x1
#define AXI_STREAM_SINK_MONITOR_IP_INTR_EN_AP_READY_MASK 0x2
#define AXI_STREAM_SINK_MONITOR_IP_INTR_EN_ALL_MASK 0x3

/* IP interrupt status register bitfields */
#define AXI_STREAM_SINK_MONITOR_IP_INTR_STS_AP_DONE_MASK 0x1
#define AXI_STREAM_SINK_MONITOR_IP_INTR_STS_AP_READY_MASK 0x2
/* CONTROL register bitfields */
#define AXI_STREAM_SINK_MONITOR_CONTROL_START_MASK 0x1
#define AXI_STREAM_SINK_MONITOR_CONTROL_CLEARTLASTCOUNT_MASK 0x2
#define AXI_STREAM_SINK_MONITOR_CONTROL_SELECTVOID_MASK 0x4
/* STATUS register bitfields */
#define AXI_STREAM_SINK_MONITOR_STATUS_IDLE_MASK 0x1
/* NUMFRAMES register bitfields */
#define AXI_STREAM_SINK_MONITOR_NUMFRAMES_NUMFRAMES_MASK 0xffffffff
/* BEATCOUNT register bitfields */
#define AXI_STREAM_SINK_MONITOR_BEATCOUNT_BEATCOUNT_MASK 0xffffffff
/* MISSCOUNT register bitfields */
#define AXI_STREAM_SINK_MONITOR_MISSCOUNT_MISSCOUNT_MASK 0xffffffff
/* ERRORCOUNT register bitfields */
#define AXI_STREAM_SINK_MONITOR_ERRORCOUNT_ERRORCOUNT_MASK 0xffffffff

#endif /* end of protection macro */
